
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Etxeb
 */
public class NewJFrame extends javax.swing.JFrame {

 
   
    
    
    
    ArrayList<Medico> medicos = new ArrayList();
    
    private final String dataBase = "hospital";
    private final String user = "root";
    private final String password = "2452169w";
    private final String URL = "jdbc:mysql://localhost:3306/"+dataBase+"?autoReconnect=true&useSSL=false";
    
    private Connection con = null;
    
    String registro;
    
    public NewJFrame() {
        initComponents();
        cargarTabla();
        setLocationRelativeTo(null); // Centrar Ventana
        radioBotonTodos.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        campoEspecialidad = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoRegistro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedicos = new javax.swing.JTable();
        BotonBuscar = new javax.swing.JButton();
        campoBuscar = new javax.swing.JTextField();
        radioBotonRegistro = new javax.swing.JRadioButton();
        radioBotonEspecialidad = new javax.swing.JRadioButton();
        radioBotonTodos = new javax.swing.JRadioButton();
        jSpinner1 = new javax.swing.JSpinner();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulario Registro Medicos"));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Apellido");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Especialidad");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("N° Registro");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Nombre");

        campoApellido.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        campoEspecialidad.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        campoNombre.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        campoRegistro.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(botonAgregar);

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(botonEliminar);

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(botonActualizar);

        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(botonLimpiar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(campoEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(77, 77, 77)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tablaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registro", "Nombre", "Apellido", "Especialidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMedicos);

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBotonRegistro);
        radioBotonRegistro.setText("Registro");

        buttonGroup1.add(radioBotonEspecialidad);
        radioBotonEspecialidad.setText("Especialidad");

        buttonGroup1.add(radioBotonTodos);
        radioBotonTodos.setText("Todos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBotonTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioBotonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBotonEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioBotonRegistro)
                            .addComponent(radioBotonEspecialidad)
                            .addComponent(radioBotonTodos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
              limpiar();  
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed

        Connection conexion;
        PreparedStatement ps;
        
        try{
            
            conexion = getConexion();
            ps = (PreparedStatement) conexion.prepareStatement("INSERT INTO medicos VALUES (?,?,?,?)");
            ps.setString(1, campoRegistro.getText());
            ps.setString(2, campoNombre.getText());
            ps.setString(3, campoApellido.getText());
            ps.setString(4, campoEspecialidad.getText());
            
            int result = ps.executeUpdate();
            
            if(result>0){
                JOptionPane.showMessageDialog(null, "Registro insertado correctamente");
                cargarTabla();
                limpiar();
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Registro no insertado");  
            }
            
            conexion.close();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error "+ex);
        }
        
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
       
        Connection conexion;
        PreparedStatement ps;
        
        try{
            
            conexion = getConexion();
            ps = (PreparedStatement) conexion.prepareStatement("DELETE FROM medicos WHERE NumRegistro=?");
            ps.setString(1, JOptionPane.showInputDialog("Ingrese el numero de registro a eliminar"));
            
            
            int result = ps.executeUpdate();
            
            if(result>0){
                JOptionPane.showMessageDialog(null, "Registro eliminado de manera exitosa");
                cargarTabla();
                limpiar();
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Registro no eliminado");  
            }
            
            conexion.close();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error "+ex);
        }
    
    }//GEN-LAST:event_botonEliminarActionPerformed

    public void cargarTabla(){
        
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaMedicos.setModel(modeloTabla);
        
        modeloTabla.addColumn("Registro");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Especialidad");
        
        
        
        PreparedStatement ps;
        ResultSet rs;
        
        
        try{
            Connection con = getConexion();
            
            ps = (PreparedStatement) con.prepareStatement("SELECT* FROM Medicos");
            rs = ps.executeQuery();
            
            while(rs.next()){
                
                Object fila[] = new Object[4];
                for (int i = 0; i <4; i++) {
                  fila[i]=rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
            
        }
        catch(SQLException e){
            System.err.println("Error "+e);
        }
        
        
        
    }
    
    
    
    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
           
           
           ResultSet rs = null;
           Connection conexion = getConexion();
           
            try {
                PreparedStatement ps = (PreparedStatement) conexion.prepareStatement("UPDATE Medicos set numRegistro=?, Nombre=?,Apellido=?, Especialidad =? WHERE NumRegistro ="+registro);
                ps.setString(1,campoRegistro.getText());
                ps.setString(2, campoNombre.getText());
                ps.setString(3, campoApellido.getText());
                ps.setString(4, campoEspecialidad.getText());
                
                int result = ps.executeUpdate();
                
                if(result>0){
                    JOptionPane.showMessageDialog(null, "Registro modificado de manera exitosa");
                    cargarTabla();
                    limpiar();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Registro no modificado");
                }
                
                conexion.close();
            
            } catch (SQLException ex) {
                
                JOptionPane.showMessageDialog(null,"Error "+ex);
            }
               
       
        
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void tablaMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMedicosMouseClicked
        ResultSet rs;

        if (tablaMedicos.getSelectedRow() >= 0) {

            registro = String.valueOf(tablaMedicos.getModel().getValueAt(tablaMedicos.getSelectedRow(), 0));

            Connection conexion = getConexion();
            try {
                PreparedStatement ps = (PreparedStatement) conexion.prepareStatement("SELECT* from Medicos Where NumRegistro=" + registro);
                rs = ps.executeQuery();

                if (rs.next()) {
                    campoNombre.setText(rs.getString("Nombre"));
                    campoApellido.setText(rs.getString("Apellido"));
                    campoEspecialidad.setText(rs.getString("Especialidad"));
                    campoRegistro.setText(rs.getString("NumRegistro"));
                }
               conexion.close();     
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error " + ex);
            }
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro de la tabla");

        }
       
    }//GEN-LAST:event_tablaMedicosMouseClicked

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        String query="";
        
        if(radioBotonTodos.isSelected()){
            query="SELECT* FROM Medicos";
        }
        
        if(radioBotonRegistro.isSelected()){
            query ="SELECT* FROM Medicos WHERE NumRegistro="+campoBuscar.getText();
        }
        
         if(radioBotonEspecialidad.isSelected()){
            query ="SELECT* FROM Medicos WHERE Especialidad LIKE '%"+campoBuscar.getText()+"%'";
        }
        
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaMedicos.setModel(modeloTabla);
        
        modeloTabla.addColumn("Registro");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Especialidad");
        
        PreparedStatement ps;
        ResultSet rs;
        
        
        try{
            Connection con = getConexion();
            
            ps = (PreparedStatement) con.prepareStatement(query);
            rs = ps.executeQuery();
            
            while(rs.next()){
                
                Object fila[] = new Object[4];
                for (int i = 0; i <4; i++) {
                  fila[i]=rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
            
        }
        catch(SQLException e){
            System.err.println("Error "+e);
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    public void limpiar(){
        campoNombre.setText("");
        campoApellido.setText("");
        campoEspecialidad.setText("");
        campoRegistro.setText("");
    }
    
    
    public Connection getConexion(){
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, user, password);

            // JOptionPane.showMessageDialog(null, "conexion exitosa");
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Error " + ex);

        }

        return con;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JTextField campoEspecialidad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoRegistro;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JRadioButton radioBotonEspecialidad;
    private javax.swing.JRadioButton radioBotonRegistro;
    private javax.swing.JRadioButton radioBotonTodos;
    private javax.swing.JTable tablaMedicos;
    // End of variables declaration//GEN-END:variables
}
