
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.net.URL;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class tablaActivos extends javax.swing.JFrame {

    ArrayList<Bodega> bodega = new ArrayList();

    private final String dataBase = "bodega";
    private final String user = "root";
    private final String password = "1234";
    private final String URL = "jdbc:mysql://localhost:3306/" + dataBase + "?autoReconnect=true&useSSL=false";

    private Connection con = null;

    public Connection getConexion() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, user, password);

            //JOptionPane.showMessageDialog(null, "conexion exitosa");
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Error " + ex);

        }

        return con;
    }

    public void cargarTabla() {

        DefaultTableModel modeloTabla = new DefaultTableModel();
        Tactivos.setModel(modeloTabla);

        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Entrada");
        modeloTabla.addColumn("T.S(en años)");
        modeloTabla.addColumn("Estatus");

        PreparedStatement ps;
        ResultSet rs;

        try {
            Connection con = getConexion();

            ps = (PreparedStatement) con.prepareStatement("SELECT* FROM activos");
            rs = ps.executeQuery();

            while (rs.next()) {

                Object fila[] = new Object[6];
                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch (SQLException e) {
            System.err.println("Error " + e);
        }
    }

    public tablaActivos() {
        initComponents();
        getConexion();
        cargarTabla();
        Rtodos.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bodegaT = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        Bcerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tactivos = new javax.swing.JTable();
        Rid = new javax.swing.JRadioButton();
        Rproducto = new javax.swing.JRadioButton();
        Rdescripcion = new javax.swing.JRadioButton();
        Bbuscar = new javax.swing.JButton();
        Tbuscar = new javax.swing.JTextField();
        Rtodos = new javax.swing.JRadioButton();
        Ractivos = new javax.swing.JRadioButton();
        Rinactivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        bodegaT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "    Producto", "Descripccion", "     Entrada"
            }
        ));
        jScrollPane1.setViewportView(bodegaT);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        Bcerrar.setText("Cerrar");
        Bcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcerrarActionPerformed(evt);
            }
        });

        Tactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "    Producto", "Descripcion", "     Entrada", "T.S(en años)", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tactivos);

        buttonGroup1.add(Rid);
        Rid.setText("Id");

        buttonGroup1.add(Rproducto);
        Rproducto.setText("Producto");

        buttonGroup1.add(Rdescripcion);
        Rdescripcion.setText("Descripcion");

        Bbuscar.setText("Buscar");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rtodos);
        Rtodos.setText("Todos");

        buttonGroup2.add(Ractivos);
        Ractivos.setText("Activos");
        Ractivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RactivosActionPerformed(evt);
            }
        });

        buttonGroup2.add(Rinactivo);
        Rinactivo.setText("Dados de baja");
        Rinactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RinactivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Mostrar:");

        jLabel2.setText("Buscar por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rid)
                                .addGap(18, 18, 18)
                                .addComponent(Rproducto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ractivos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Rinactivo)))
                        .addGap(16, 16, 16)
                        .addComponent(Rdescripcion)
                        .addGap(18, 18, 18)
                        .addComponent(Rtodos)
                        .addGap(37, 37, 37)
                        .addComponent(Tbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bbuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(Bcerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Ractivos)
                    .addComponent(Rinactivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Rid)
                    .addComponent(Rproducto)
                    .addComponent(Rdescripcion)
                    .addComponent(Rtodos)
                    .addComponent(Tbuscar)
                    .addComponent(Bbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Bcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BcerrarActionPerformed

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuscarActionPerformed
        String query = "";
        if (Rtodos.isSelected()) {
            query = "SELECT* FROM activos";
        }

        if (Rid.isSelected()) {
            query = "SELECT* FROM activos WHERE id=" + Tbuscar.getText();
        }

        if (Rproducto.isSelected()) {
            query = "SELECT* FROM activos WHERE producto LIKE '%" + Tbuscar.getText() + "%'";
        }

        if (Rdescripcion.isSelected()) {
            query = "SELECT* FROM activos WHERE descripcion LIKE '%" + Tbuscar.getText() + "%'";
        }

        DefaultTableModel modeloTabla = new DefaultTableModel();
        Tactivos.setModel(modeloTabla);

        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Entrada");
        modeloTabla.addColumn("T.S(en años)");
        modeloTabla.addColumn("Estatus");

        PreparedStatement ps;
        ResultSet rs;

        try {
            Connection con = getConexion();

            ps = (PreparedStatement) con.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {

                Object fila[] = new Object[6];
                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }

        } catch (SQLException e) {
            System.err.println("Error " + e);
        }

    }//GEN-LAST:event_BbuscarActionPerformed

    private void RactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RactivosActionPerformed
        String si = "si";
        String query = "";
        if (Ractivos.isSelected()) {
            query = "SELECT* FROM activos WHERE estatus LIKE '%" + si + "%'";

        }
        DefaultTableModel modeloTabla = new DefaultTableModel();
        Tactivos.setModel(modeloTabla);

        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Entrada");
        modeloTabla.addColumn("T.S(en años)");
        modeloTabla.addColumn("Estatus");
        PreparedStatement ps;
        ResultSet rs;
        try {
            Connection con = getConexion();

            ps = (PreparedStatement) con.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {

                Object fila[] = new Object[6];
                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }

        } catch (SQLException e) {
            System.err.println("Error " + e);
        }

    }//GEN-LAST:event_RactivosActionPerformed

    private void RinactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RinactivoActionPerformed
        String si = "si";
        String no = "no";
        String query = "";
        if (Rinactivo.isSelected()) {
            query = "SELECT* FROM activos WHERE estatus LIKE '%" + no + "%'";

        }
        DefaultTableModel modeloTabla = new DefaultTableModel();
        Tactivos.setModel(modeloTabla);

        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Entrada");
        modeloTabla.addColumn("T.S(en años)");
        modeloTabla.addColumn("Estatus");
        PreparedStatement ps;
        ResultSet rs;
        try {
            Connection con = getConexion();

            ps = (PreparedStatement) con.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {

                Object fila[] = new Object[6];
                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }

        } catch (SQLException e) {
            System.err.println("Error " + e);
        }


    }//GEN-LAST:event_RinactivoActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablaActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablaActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablaActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablaActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablaActivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bbuscar;
    private javax.swing.JButton Bcerrar;
    private javax.swing.JRadioButton Ractivos;
    private javax.swing.JRadioButton Rdescripcion;
    private javax.swing.JRadioButton Rid;
    private javax.swing.JRadioButton Rinactivo;
    private javax.swing.JRadioButton Rproducto;
    private javax.swing.JRadioButton Rtodos;
    private javax.swing.JTable Tactivos;
    private javax.swing.JTextField Tbuscar;
    private javax.swing.JTable bodegaT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
